"""empty message

Revision ID: 59c411f2233a
Revises: d7180d9c2aeb
Create Date: 2021-07-27 13:28:22.793561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c411f2233a'
down_revision = 'd7180d9c2aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('short_desc', sa.String(), nullable=True))
    op.add_column('products', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'desc')
    op.drop_column('products', 'short_desc')
    # ### end Alembic commands ###
