"""Products table

Revision ID: 62ffe9062174
Revises: 
Create Date: 2021-05-30 19:31:02.968867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ffe9062174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('rendered_data', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discunted', sa.Integer(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('data_gallery', sa.LargeBinary(), nullable=True),
    sa.Column('rendered_gallery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
