"""add date column

Revision ID: 97c2893f1674
Revises: 7cd424f2544f
Create Date: 2021-06-16 09:54:27.771325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c2893f1674'
down_revision = '7cd424f2544f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'date')
    # ### end Alembic commands ###
