"""empty message

Revision ID: e2d5534c7a77
Revises: aa7c279bfe77
Create Date: 2021-07-21 21:43:23.535935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d5534c7a77'
down_revision = 'aa7c279bfe77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
