"""update tables

Revision ID: e6603c4bcd40
Revises: bc19c002349d
Create Date: 2021-07-04 12:17:55.368623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6603c4bcd40'
down_revision = 'bc19c002349d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    op.drop_column('cart', 'total')
    op.drop_column('cart', 'photo')
    op.drop_column('cart', 'discounted')
    op.drop_column('cart', 'number')
    op.drop_column('cart', 'price')
    op.drop_column('cart', 'amount')
    op.drop_column('cart', 'inventory')
    op.drop_column('cart', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('inventory', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('amount', sa.FLOAT(), nullable=True))
    op.add_column('cart', sa.Column('price', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('number', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('discounted', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('photo', sa.VARCHAR(length=200), nullable=True))
    op.add_column('cart', sa.Column('total', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'user_id')
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###
