"""empty message

Revision ID: fa5e9e5cf8b6
Revises: be6e0b9f59f3
Create Date: 2021-08-02 13:03:23.616303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5e9e5cf8b6'
down_revision = 'be6e0b9f59f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'number')
    # ### end Alembic commands ###
